// This runner is auto-generated by Brittle

runTests()

async function runTests () {
  const test = (await import('brittle')).default

  test.pause()

  await import('./flow.js')
  await import('./sessions.js')
  await import('./snapshot.js')

  test.resume()
}
